### 
POST http://localhost:5000/api/v2/auth/login
content-type: application/json

{
"username": "Egor Egorov",
"password": "secret11"
}

### 
DELETE http://localhost:5000/api/v2/auth/login
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVnb3IgRWdvcm92IiwiaWQiOjQsImlhdCI6MTY3NjI5NDE5OCwiZXhwIjoxNjc3MTU4MTk4fQ.SmfFmYoniJCPKj88K2l9G4cKvi9Le-soNHueoAX1hmc